version: '3.7'

networks:
  traefik-public:
    external: true
#  interna:
#    external: false

services:

# Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik-public
    security_opt:
      - no-new-privileges:true
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    environment:
      - TZ=America/Maceio
    labels:
      - traefik.enable=true
      - traefik.network=traefik-public
      - traefik.http.routers.portainer-rtr.entrypoints=websecure
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer-test.testsystem.tech`)
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
#    deploy:
#      placement:
#        constraints:
#          - node.labels.traefik-data == true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      # Use the custom label "traefik-label=traefik-cbm-hml-03"
      # This Traefik will only use services with this label
      # That way you can add other internal Traefik instances per stack if needed
      #- traefik.label=cbm-prod-05
      # Using the environment variables USERNAME and HASHED_PASSWORD
      #- traefik.http.middlewares.basic-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      #Redirecionamento global para https
#        - traefik.http.routers.http-catchall.entrypoints=http
#        - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
#        - traefik.http.routers.http-catchall.middlewares=redirect-to-https
#        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
#        - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # Uses the environment variable DOMAIN
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik-test.testsystem.tech`)
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=testsystem.tech
      # Enable HTTP Basic auth, using the middleware created above
      - traefik.http.routers.traefik-rtr.middlewares=basic-auth@file
      # Define the port inside of the Docker service to use
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080
    volumes:
      - ./traefik/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      #- --providers.docker.swarmmode
      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      # - --providers.docker.constraints=Label(`traefik.label`, `cbm-prod-05`)
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.web.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.websecure.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.letsencrypt.acme.email=guilhermebraz089@gmail.com
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Uso de Let's Encrypt staging server para testes
      #- --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # Load dynamic configuration from one or more .toml or .yml files in a directory.
      - --providers.file.directory=/rules
      # Only works on top level files in the rules folder
      - --providers.file.watch=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      #Enable Traefi Pilot
#      - --pilot.token=511af1ef-54f2-498f-9369-7e3798bda3b6
    networks:
      - traefik-public

  laravel:
    #nome do container definido usando o valor da variável
    container_name: laravel
    #imagem do container que será baixada do repositório dockerhub ou harbor
    #image: harbor.dev.cbm.al.gov.br/dev-local/cakephp:5.6
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: harbor.dev.cbm.al.gov.br/dev-local/node
    #image: nginxdemos/hello
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - traefik-public
 #     - interna
    #seção onde é definida a montagem bind para o volume da aplicação em desenvolvimento
    #Necessário mapear diretório do host que contém a aplicação a ser desenvolvida
    volumes:
      - ./laravel:/app
    environment:
      - APP_ENV=local
    labels:
      - traefik.enable=true
      - traefik.network=traefik-public
      #definição da porta de entrada do traefik proxy
      - traefik.http.routers.laravel-rtr.entrypoints=websecure
      #definição da rota via traefik proxy
      - traefik.http.routers.laravel-rtr.rule=Host(`laravel-test.testsystem.tech`)
      - traefik.http.routers.laravel-rtr.tls=true
      - traefik.http.routers.laravel-rtr.tls.certresolver=letsencrypt
      #definição do serviço via traefik proxy
      - traefik.http.services.laravel-svc.loadbalancer.server.port=80
      - traefik.http.routers.laravel-rtr.middlewares=basic-auth@file
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    #ports:
    #  - 3306:3306
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - traefik-public
#      - interna
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: pwb
      MYSQL_DATABASE: pwb
      MYSQL_USER: pwb
      MYSQL_PASSWORD: pwb   

############ phpmyadmim ############
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=pwb
      - PMA_HOST=mysql
      - TZ=America/Maceio
    ports:
      - '9090:80'
    depends_on:
      - mysql
    networks:
      - traefik-public
 #     - interna
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      ## HTTP Routers
      - traefik.http.routers.phpmyadmin-rtr.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-rtr.rule=Host(`phpmyadmin-test.testsystem.tech`)
      - traefik.http.routers.phpmyadmin-rtr.tls=true
      - traefik.http.routers.phpmyadmin-rtr.tls.certresolver=letsencrypt
      ## HTTP Services
      - traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80
      - traefik.http.routers.phpmyadmim-rtr.middlewares=basic-auth@file